name: 'shopify_holistic_reporting'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<3.0.0"]
models:
  shopify_holistic_reporting:
    +materialized: table
    +schema: shopify_holistic
    intermediate:
      +materialized: view
vars:
  shopify_holistic_reporting:
    klaviyo__email_attribution_lookback: 120
    klaviyo__sms_attribution_lookback: 24
    klaviyo__eligible_attribution_events: # default in klaviyo -> https://help.klaviyo.com/hc/en-us/articles/115005248128 
    - 'opened email'
    - 'clicked email'
    - 'clicked sms'

    klaviyo__count_metrics:
    - 'Active on Site'   # default API metrics
    - 'Viewed Product'
    - 'Ordered Product'   # some default Shopify metrics
    - 'Placed Order'   # there are X 'ordered product' events for every `placed order` purchase event of X products
    - 'Refunded Order'   # note: klaviyo only tracks FULL refunds (not partial)
    - 'Received Email'   # default email and sms conversion metrics in Klaviyo
    - 'Clicked Email'
    - 'Opened Email'
    - 'Marked Email as Spam'
    - 'Unsubscribed'
    - 'Received SMS'
    - 'Clicked SMS'
    - 'Sent SMS'
    - 'Unsubscribed from SMS'

    klaviyo__sum_revenue_metrics:
    - 'Refunded Order'
    - 'Placed Order'
    - 'Ordered Product'
    - 'checkout started'
    - 'cancelled order'
