name: 'shopify_holistic_reporting_integration_tests'
version: '0.1.1'
profile: 'integration_tests'
config-version: 2


vars:
  shopify_source:
    customer_source: "{{ ref('shopify_customer_data') }}"
    order_line_refund_source: "{{ ref('shopify_order_line_refund_data') }}"
    order_line_source: "{{ ref('shopify_order_line_data') }}"
    order_source: "{{ ref('shopify_order_data') }}"
    product_source: "{{ ref('shopify_product_data') }}"
    order_adjustment_source: "{{ ref('shopify_order_adjustment_data') }}"
    product_variant_source: "{{ ref('shopify_product_variant_data') }}"
    refund_source: "{{ ref('shopify_refund_data') }}"
    transaction_source: "{{ ref('shopify_transaction_data') }}"

  klaviyo_source:
    event_table: "{{ ref('event') }}" 
    campaign: "{{ ref('campaign') }}" 
    flow: "{{ fivetran_utils.snowflake_seed_data('flow') }}" 
    integration: "{{ ref('integration') }}" 
    person: "{{ ref('person') }}" 
    metric: "{{ ref('metric') }}" 
    klaviyo__event_pass_through_columns: []
    klaviyo__person_pass_through_columns: []
  
  klaviyo:
    klaviyo__eligible_attribution_events: # default in klaviyo -> https://help.klaviyo.com/hc/en-us/articles/115005248128 
      - 'opened email'
      - 'clicked email'
      - 'clicked sms'

    klaviyo__count_metrics: 
      - 'Active on Site' # default API metrics
      - 'Viewed Product'
      - 'Ordered Product' # default Shopify metrics
      - 'Placed Order'
      - 'Refunded Order' # note: klaviyo only tracks FULL refunds (not partial)
      - 'Cancelled Order'
      - 'Fulfilled Order'
      - 'Received Email' # default email and sms conversion metrics in Klaviyo
      - 'Clicked Email'
      - 'Opened Email'
      - 'Bounced Email'
      - 'Marked Email as Spam'
      - 'Dropped Email'
      - 'Subscribed to List'
      - 'Unsubscribed to List'
      - 'Unsubscribed'
      - 'Updated Email Preferences'
      - 'Subscribed to Back in Stock'
      - 'Merged Profile'
      - 'Received SMS'
      - 'Clicked SMS'
      - 'Consented to Receive SMS'
      - 'Sent SMS'
      - 'Unsubscribed from SMS'
      - 'Failed to Deliver SMS'

    klaviyo__sum_revenue_metrics:
      - 'Refunded Order'
      - 'Placed Order'
      - 'Ordered Product'
      - 'checkout started'
      - 'cancelled order'
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['shopify_holistic_reporting','spark_utils', 'dbt_utils']
    
seeds:
  shopify_holistic_reporting_integration_tests:
  # shopify
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    +column_types:
      _fivetran_synced: timestamp
    shopify_customer_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        default_address_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        processed_at: timestamp
        cancelled_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        customer_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_data:
      +column_types:
        _fivetran_synced: timestamp
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        variant_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_refund_data:
      +column_types:
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_line_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        published_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_adjustment_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_variant_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        inventory_item_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_transaction_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        receipt: "{{ 'varchar(100)' if target.name in ('redshift', 'postgres') else 'string' }}"
    shopify_refund_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    # klaviyo
    person:
      +column_types:
        phone_number: "{{ 'string' if target.type in ('bigquery', 'spark') else 'varchar' }}"
    flow:
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        trigger: "{{ 'string' if target.type in ('bigquery', 'spark') else 'varchar' }}"
    flow_snowflake:
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    event:
      +column_types:
        flow_id: "{{ 'string' if target.type in ('bigquery', 'spark') else 'varchar' }}"
        campaign_id: "{{ 'string' if target.type in ('bigquery', 'spark') else 'varchar' }}"
