name: 'shopify_holistic_reporting_integration_tests'
version: '0.3.1'
profile: 'integration_tests'
config-version: 2

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

quoting:
  identifier: "{{ target.type == 'snowflake' }}"

vars:
  shopify_source:
    shopify_schema: 'shopify_holistic_reporting_integration_tests_1'
    # customer_source: "{{ ref('customer') }}"
    # order_line_refund_source: "{{ ref('order_line_refund') }}"
    # order_line_source: "{{ ref('order_line') }}"
    # order_source: "{{ ref('order') }}"
    # product_source: "{{ ref('product') }}"
    # order_adjustment_source: "{{ ref('order_adjustment') }}"
    # product_variant_source: "{{ ref('product_variant') }}"
    # refund_source: "{{ ref('refund') }}"
    # transaction_source: "{{ ref('transaction') }}"
    
  klaviyo_source:
    klaviyo_schema: 'shopify_holistic_reporting_integration_tests_1'
    event_table: "{{ ref('event') }}" 
    campaign: "{{ ref('campaign') }}" 
    flow: "{{ fivetran_utils.snowflake_seed_data('flow') }}" 
    integration: "{{ ref('integration') }}" 
    person: "{{ ref('person') }}" 
    metric: "{{ ref('metric') }}" 
    klaviyo__event_pass_through_columns: []
    klaviyo__person_pass_through_columns: []
  
  klaviyo:
    klaviyo__eligible_attribution_events: # default in klaviyo -> https://help.klaviyo.com/hc/en-us/articles/115005248128 
      - 'opened email'
      - 'clicked email'
      - 'clicked sms'

    klaviyo__count_metrics: 
      - 'Active on Site' # default API metrics
      - 'Viewed Product'
      - 'Ordered Product' # default Shopify metrics
      - 'Placed Order'
      - 'Refunded Order' # note: klaviyo only tracks FULL refunds (not partial)
      - 'Cancelled Order'
      - 'Fulfilled Order'
      - 'Received Email' # default email and sms conversion metrics in Klaviyo
      - 'Clicked Email'
      - 'Opened Email'
      - 'Bounced Email'
      - 'Marked Email as Spam'
      - 'Dropped Email'
      - 'Subscribed to List'
      - 'Unsubscribed to List'
      - 'Unsubscribed'
      - 'Updated Email Preferences'
      - 'Subscribed to Back in Stock'
      - 'Merged Profile'
      - 'Received SMS'
      - 'Clicked SMS'
      - 'Consented to Receive SMS'
      - 'Sent SMS'
      - 'Unsubscribed from SMS'
      - 'Failed to Deliver SMS'

    klaviyo__sum_revenue_metrics:
      - 'Refunded Order'
      - 'Placed Order'
      - 'Ordered Product'
      - 'checkout started'
      - 'cancelled order'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['shopify_holistic_reporting', 'spark_utils', 'dbt_utils']
    
seeds:
  shopify_holistic_reporting_integration_tests:
  # shopify
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    +column_types:
      _fivetran_synced: timestamp
    customer:
      +tags: shopify
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        default_address_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        accepts_marketing: boolean
    order:
      +tags: shopify
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        processed_at: timestamp
        cancelled_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        customer_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    order_line:
      +tags: shopify
      +column_types:
        _fivetran_synced: timestamp
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        variant_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    order_line_refund:
      +tags: shopify
      +column_types:
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_line_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    product:
      +tags: shopify
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        published_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    order_adjustment:
      +tags: shopify
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    product_variant:
      +tags: shopify
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        inventory_item_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    transaction:
      +tags: shopify
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        receipt: "{{ 'varchar(100)' if target.name in ('redshift', 'postgres') else 'string' }}"
    refund:
      +tags: shopify
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    # klaviyo
    person:
      +tags: klaviyo
      +column_types:
        phone_number: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow:
      +tags: klaviyo
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        trigger: "{{ 'string' if target.type in  ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow_snowflake:
      +tags: klaviyo
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    event:
      +tags: klaviyo
      +column_types:
        flow_id: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        campaign_id: "{{ 'string' if target.type in  ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        datetime: timestamp
        timestamp: timestamp
    integration:
      +tags: klaviyo
    metric:
      +tags: klaviyo
    campaign:
      +tags: klaviyo