name: 'shopify_holistic_reporting_integration_tests'
version: '0.4.0'
profile: 'integration_tests'
config-version: 2

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

vars:
  shopify_source:
    shopify_schema: 'shopify_holistic_reporting_integration_tests_1'
    # shopify_customer_identifier:          "customer"
    # shopify_order_line_refund_identifier: "order_line_refund"
    # shopify_order_line_identifier:        "order_line"
    shopify_order_identifier:             'order_table' # reserved keyword in snowflake
    # shopify_product_identifier:           "product"
    # shopify_order_adjustment_identifier:  "order_adjustment"
    # shopify_product_variant_identifier:   "product_variant"
    # shopify_refund_identifier:            "refund"
    # shopify_transaction_identifier:       "transaction"
    # shopify_abandoned_checkout_identifier: "abandoned_checkout"
    # shopify_collection_product_identifier: "collection_product"
    # shopify_collection_identifier: "collection"
    # shopify_customer_tag_identifier: "customer_tag"
    # shopify_discount_code_identifier: "discount_code"
    # shopify_fulfillment_identifier: "fulfillment"
    # shopify_fulfillment_event_identifier: "fulfillment_event"
    # shopify_inventory_item_identifier: "inventory_item"
    # shopify_inventory_level_identifier: "inventory_level"
    # shopify_location_identifier: "location"
    # shopify_metafield_identifier: "metafield"
    # shopify_order_note_attribute_identifier: "order_note_attribute"
    # shopify_order_shipping_line_identifier: "order_shipping_line"
    # shopify_order_shipping_tax_line_identifier: "order_shipping_tax_line"
    # shopify_order_tag_identifier: "order_tag"
    # shopify_order_url_tag_identifier: "order_url_tag"
    # shopify_price_rule_identifier: "price_rule"
    # shopify_product_image_identifier: "product_image"
    # shopify_product_tag_identifier: "product_tag"
    # shopify_shop_identifier: "shop"
    # shopify_tax_line_identifier: "tax_line"
    # shopify_tender_transaction_identifier: "tender_transaction"
    # shopify_abandoned_checkout_discount_code_identifier: "abandoned_checkout_discount_code"
    # shopify_order_discount_code_identifier: "order_discount_code"
    # shopify_abandoned_checkout_shipping_line_identifier: "abandoned_checkout_shipping_line"
    
  klaviyo_source:
    klaviyo_schema: 'shopify_holistic_reporting_integration_tests_1'
    # klaviyo_campaign_identifier: "campaign"
    # klaviyo_event_identifier: "event"
    # klaviyo_flow_identifier: "flow"
    # klaviyo_integration_identifier: "integration"
    # klaviyo_person_identifier: "person"
    # klaviyo_metric_identifier: "metric"
    klaviyo__event_pass_through_columns: []
    klaviyo__person_pass_through_columns: []

  klaviyo:
    klaviyo__eligible_attribution_events: # default in klaviyo -> https://help.klaviyo.com/hc/en-us/articles/115005248128 
      - 'opened email'
      - 'clicked email'
      - 'clicked sms'

    klaviyo__count_metrics: 
      - 'Active on Site' # default API metrics
      - 'Viewed Product'
      - 'Ordered Product' # default Shopify metrics
      - 'Placed Order'
      - 'Refunded Order' # note: klaviyo only tracks FULL refunds (not partial)
      - 'Cancelled Order'
      - 'Fulfilled Order'
      - 'Received Email' # default email and sms conversion metrics in Klaviyo
      - 'Clicked Email'
      - 'Opened Email'
      - 'Bounced Email'
      - 'Marked Email as Spam'
      - 'Dropped Email'
      - 'Subscribed to List'
      - 'Unsubscribed to List'
      - 'Unsubscribed'
      - 'Updated Email Preferences'
      - 'Subscribed to Back in Stock'
      - 'Merged Profile'
      - 'Received SMS'
      - 'Clicked SMS'
      - 'Consented to Receive SMS'
      - 'Sent SMS'
      - 'Unsubscribed from SMS'
      - 'Failed to Deliver SMS'

    klaviyo__sum_revenue_metrics:
      - 'Refunded Order'
      - 'Placed Order'
      - 'Ordered Product'
      - 'checkout started'
      - 'cancelled order'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['shopify_holistic_reporting', 'spark_utils', 'dbt_utils']
    
# quoting:
#   database: "{{ target.type == 'snowflake' }}"
#   schema: "{{ target.type == 'snowflake' }}"
#   identifier: "{{ target.type == 'snowflake' }}"

seeds:
  shopify_holistic_reporting_integration_tests:
  # shopify
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    +column_types:
      _fivetran_synced: timestamp
    customer:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        default_address_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        email: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    order:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        processed_at: timestamp
        cancelled_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        customer_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
      +alias: order_table
    order_line:
      +column_types:
        _fivetran_synced: timestamp
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        variant_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    order_line_refund:
      +column_types:
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_line_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    product:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        published_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    order_adjustment:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    product_variant:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        inventory_item_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    transaction:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        receipt: "{{ 'varchar(100)' if target.name in ('redshift', 'postgres') else 'string' }}"
    refund:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    abandoned_checkout_discount_code:
      +column_types:
        amount: float
        created_at: timestamp
        updated_at: timestamp
    abandoned_checkout:
      +column_types:
        total_line_items_price: float
        billing_address_phone: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        shipping_address_phone: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        closed_at: timestamp
        created_at: timestamp
        updated_at: timestamp
        _fivetran_deleted: boolean
    discount_code:
      +column_types:
        usage_count: float
    order_discount_code:
      +column_types:
        amount: float
    order_shipping_tax_line:
      +column_types:
        price: float
    order_shipping_line:
      +column_types:
        discounted_price: float
        price: float
    price_rule:
      +column_types:
        prerequisite_subtotal_range: float
        value: float
    collection:
      +column_types:
        disjunctive: boolean
        published_at: timestamp
        updated_at: timestamp
        title: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    metafield:
      +column_types:
        value_type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    shop:
      +column_types:
        taxes_included: boolean
        google_apps_login_enabled: boolean
        county_taxes: boolean
    inventory_level:
      +column_types:
        updated_at: timestamp
    inventory_item:
      +column_types:
        updated_at: timestamp
        created_at: timestamp
    abandoned_checkout_shipping_line:
      +column_types:
        markup: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        price: float
        original_shop_markup: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        original_shop_price: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    tax_line:
      +column_types:
        price: float
        rate: float
    # klaviyo
    person:
      +tags: klaviyo
      +column_types:
        phone_number: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow:
      +tags: klaviyo
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        trigger: "{{ 'string' if target.type in  ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow_snowflake:
      +tags: klaviyo
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    event:
      +tags: klaviyo
      +column_types:
        flow_id: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        campaign_id: "{{ 'string' if target.type in  ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        datetime: timestamp
        timestamp: timestamp
    integration:
      +tags: klaviyo
    metric:
      +tags: klaviyo
    campaign:
      +tags: klaviyo