name: 'shopify_holistic_reporting_integration_tests'
version: '0.3.1'
profile: 'integration_tests'
config-version: 2

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

vars:
  shopify_source:
    shopify_union_schemas: ['shopify_holistic_reporting_integration_tests_1']
    shopify_customer_identifier:          "shopify_customer_data"
    shopify_order_line_refund_identifier: "shopify_order_line_refund_data"
    shopify_order_line_identifier:        "shopify_order_line_data"
    shopify_order_identifier:             "shopify_order_data"
    shopify_product_identifier:           "shopify_product_data"
    shopify_order_adjustment_identifier:  "shopify_order_adjustment_data"
    shopify_product_variant_identifier:   "shopify_product_variant_data"
    shopify_refund_identifier:            "shopify_refund_data"
    shopify_transaction_identifier:       "shopify_transaction_data"
    shopify_abandoned_checkout_identifier: "shopify_abandoned_checkout_data"
    shopify_collection_product_identifier: "shopify_collection_product_data"
    shopify_collection_identifier: "shopify_collection_data"
    shopify_customer_tag_identifier: "shopify_customer_tag_data"
    shopify_discount_code_identifier: "shopify_discount_code_data"
    shopify_fulfillment_identifier: "shopify_fulfillment_data"
    shopify_fulfillment_event_identifier: "shopify_fulfillment_event_data"
    shopify_inventory_item_identifier: "shopify_inventory_item_data"
    shopify_inventory_level_identifier: "shopify_inventory_level_data"
    shopify_location_identifier: "shopify_location_data"
    shopify_metafield_identifier: "shopify_metafield_data"
    shopify_order_note_attribute_identifier: "shopify_order_note_attribute_data"
    shopify_order_shipping_line_identifier: "shopify_order_shipping_line_data"
    shopify_order_shipping_tax_line_identifier: "shopify_order_shipping_tax_line_data"
    shopify_order_tag_identifier: "shopify_order_tag_data"
    shopify_order_url_tag_identifier: "shopify_order_url_tag_data"
    shopify_price_rule_identifier: "shopify_price_rule_data"
    shopify_product_image_identifier: "shopify_product_image_data"
    shopify_product_tag_identifier: "shopify_product_tag_data"
    shopify_shop_identifier: "shopify_shop_data"
    shopify_tax_line_identifier: "shopify_tax_line_data"
    shopify_tender_transaction_identifier: "shopify_tender_transaction_data"
    shopify_abandoned_checkout_discount_code_identifier: "shopify_abandoned_checkout_discount_code_data"
    shopify_order_discount_code_identifier: "shopify_order_discount_code_data"
    shopify_abandoned_checkout_shipping_line_identifier: "shopify_abandoned_checkout_shipping_line_data"
    
  klaviyo_source:
    klaviyo_union_schemas: ['shopify_holistic_reporting_integration_tests_1']
    klaviyo_campaign_identifier: "campaign"
    klaviyo_event_identifier: "event"
    klaviyo_flow_identifier: "flow"
    klaviyo_integration_identifier: "integration"
    klaviyo_person_identifier: "person"
    klaviyo_metric_identifier: "metric"
    klaviyo__event_pass_through_columns: []
    klaviyo__person_pass_through_columns: []

  klaviyo:
    klaviyo__eligible_attribution_events: # default in klaviyo -> https://help.klaviyo.com/hc/en-us/articles/115005248128 
      - 'opened email'
      - 'clicked email'
      - 'clicked sms'

    klaviyo__count_metrics: 
      - 'Active on Site' # default API metrics
      - 'Viewed Product'
      - 'Ordered Product' # default Shopify metrics
      - 'Placed Order'
      - 'Refunded Order' # note: klaviyo only tracks FULL refunds (not partial)
      - 'Cancelled Order'
      - 'Fulfilled Order'
      - 'Received Email' # default email and sms conversion metrics in Klaviyo
      - 'Clicked Email'
      - 'Opened Email'
      - 'Bounced Email'
      - 'Marked Email as Spam'
      - 'Dropped Email'
      - 'Subscribed to List'
      - 'Unsubscribed to List'
      - 'Unsubscribed'
      - 'Updated Email Preferences'
      - 'Subscribed to Back in Stock'
      - 'Merged Profile'
      - 'Received SMS'
      - 'Clicked SMS'
      - 'Consented to Receive SMS'
      - 'Sent SMS'
      - 'Unsubscribed from SMS'
      - 'Failed to Deliver SMS'

    klaviyo__sum_revenue_metrics:
      - 'Refunded Order'
      - 'Placed Order'
      - 'Ordered Product'
      - 'checkout started'
      - 'cancelled order'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['shopify_holistic_reporting', 'spark_utils', 'dbt_utils']
    
seeds:
  shopify_holistic_reporting_integration_tests:
  # shopify
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    +column_types:
      _fivetran_synced: timestamp
    shopify_customer_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        default_address_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        email: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    shopify_order_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        processed_at: timestamp
        cancelled_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        customer_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_data:
      +column_types:
        _fivetran_synced: timestamp
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        variant_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_line_refund_data:
      +column_types:
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        location_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_line_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
        published_at: timestamp
        _fivetran_synced: timestamp
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_order_adjustment_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_product_variant_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        product_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        inventory_item_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_transaction_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        refund_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        receipt: "{{ 'varchar(100)' if target.name in ('redshift', 'postgres') else 'string' }}"
    shopify_refund_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        order_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    shopify_abandoned_checkout_discount_code_data:
      +column_types:
        amount: float
        created_at: timestamp
        updated_at: timestamp
    shopify_abandoned_checkout_data:
      +column_types:
        total_line_items_price: float
        billing_address_phone: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        shipping_address_phone: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        closed_at: timestamp
        created_at: timestamp
        updated_at: timestamp
        _fivetran_deleted: boolean
    shopify_discount_code_data:
      +column_types:
        usage_count: float
    shopify_order_discount_code_data:
      +column_types:
        amount: float
    shopify_order_shipping_tax_line_data:
      +column_types:
        price: float
    shopify_order_shipping_line_data:
      +column_types:
        discounted_price: float
        price: float
    shopify_price_rule_data:
      +column_types:
        prerequisite_subtotal_range: float
        value: float
    shopify_collection_data:
      +column_types:
        disjunctive: boolean
        published_at: timestamp
        updated_at: timestamp
        title: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    shopify_metafield_data:
      +column_types:
        value_type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        type: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    shopify_shop_data:
      +column_types:
        taxes_included: boolean
        google_apps_login_enabled: boolean
        county_taxes: boolean
    shopify_inventory_level_data:
      +column_types:
        updated_at: timestamp
    shopify_inventory_item_data:
      +column_types:
        updated_at: timestamp
        created_at: timestamp
    shopify_abandoned_checkout_shipping_line_data:
      +column_types:
        markup: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        price: float
        original_shop_markup: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        original_shop_price: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    shopify_tax_line_data:
      +column_types:
        price: float
        rate: float
    # klaviyo
    person:
      +tags: klaviyo
      +column_types:
        phone_number: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow:
      +tags: klaviyo
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        trigger: "{{ 'string' if target.type in  ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow_snowflake:
      +tags: klaviyo
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    event:
      +tags: klaviyo
      +column_types:
        flow_id: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        campaign_id: "{{ 'string' if target.type in  ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        datetime: timestamp
        timestamp: timestamp
    integration:
      +tags: klaviyo
    metric:
      +tags: klaviyo
    campaign:
      +tags: klaviyo